name: FirstMcDE-RPGSword
author: VIPMarcel
description: This plugin add the rpg-sword
version: 1.0-SNAPSHOT
api-version: 1.18

depend: [WorldGuard, WorldGuardEvents]

main: vip.marcel.firstmc.RPGSword

commands:
  fixsword:
    description: gives you the rpg-sword
  prestige:
    description: updates your prestige level