name: FirstMcDE-RPGSword
author: VIPMarcel
description: This plugin add the rpg-sword
version: 1.0-SNAPSHOT
api-version: 1.18

depend: [WorldGuard, WorldGuardEvents]

main: vip.marcel.firstmc.RPGSword

permissions:
  rpg.shop.skills.strenght1.on:
    default: false
  rpg.shop.skills.strenght2.on:
    default: false
  rpg.shop.skills.speed1.on:
    default: false
  rpg.shop.skills.speed2.on:
    default: false
  rpg.shop.skills.nightvision.on:
    default: false
  rpg.shop.skills.jumpboost1.on:
    default: false
  rpg.shop.skills.jumpboost2.on:
    default: false
  rpg.shop.skills.regeneration1.on:
    default: false
  rpg.shop.skills.regeneration2.on:
    default: false
  rpg.admin:
    default: OP
  rpg.command.levelbox:
    default: OP
  rpg.command.setposition:
    default: OP
  rpg.command.editmode:
    default: OP

commands:
  fixsword:
    description: gives you the rpg-sword
  prestige:
    description: updates your prestige level
  rpg:
    description: official rpg command
  coinshop:
    description: opens the rpg-coins shop
    aliases: [coinsshop, cshop]
  skills:
    description: opens your bought skills inventory
  coins:
    description: shows your coins amount
  levelbox:
    description: teleports to your current level, loot area
  setposition:
    description: create a server location point
  editmode:
    description: sets you in edit mode, to change the map
    aliases: [buildmode]
  prestigetop:
    description: shows you the top 10 prestige level players
  discord:
    description: shows the discord url
  adress:
    description: shows the server adress
    aliases: [ip, server]
  afk:
    description: teleports to the afk area
    aliases: [awayfromkeyboard]
  coinstop:
    description: shows you the top 10 rpg-coins players
  achievments:
    description: shows your granted achievements